AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ValidateJsonFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket
      MemorySize: 128
      Timeout: 5
      Policies:
      - AWSLambdaBasicExecutionRole
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /validatejson
            Method: get
    Metadata:
      SamResourceId: ValidateJsonFunction
Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ValidateJson
  ValidateJsonFunction:
    Description: ValidateJson Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ValidateJsonFunction
      - Arn
  ValidateJsonFunctionIamRole:
    Description: Implicit IAM Role created for ValidateJson function
    Value:
      Fn::GetAtt:
      - ValidateJsonFunctionRole
      - Arn
